/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mapr_security_JNISecurity_MutableErr */

#ifndef _Included_com_mapr_security_JNISecurity_MutableErr
#define _Included_com_mapr_security_JNISecurity_MutableErr
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
