/* Copyright (c) 2009 & onwards. MapR Tech, Inc., All rights reserved */
#ifndef FILEIDS_H__
#define FILEIDS_H__
namespace mapr {
namespace fs {

namespace FileId {
  enum {
    FS_CLIENT_FILECLIENT_CC_TABLE_CC,    /* fs/client/fileclient/cc/table.cc */
    FS_CLIENT_FILECLIENT_CC_FIDMAP_CC,    /* fs/client/fileclient/cc/fidmap.cc */
    FS_CLIENT_FILECLIENT_CC_SHMEM_CC,    /* fs/client/fileclient/cc/shmem.cc */
    FS_CLIENT_FILECLIENT_CC_TEST_CC,    /* fs/client/fileclient/cc/test.cc */
    FS_CLIENT_FILECLIENT_CC_CIDCACHE_CC,    /* fs/client/fileclient/cc/cidcache.cc */
    FS_CLIENT_FILECLIENT_CC_JNI_COMMON_CC,    /* fs/client/fileclient/cc/jni_common.cc */
    FS_CLIENT_FILECLIENT_CC_INODE_CC,    /* fs/client/fileclient/cc/inode.cc */
    FS_CLIENT_FILECLIENT_CC_FILEOPS_CC,    /* fs/client/fileclient/cc/fileops.cc */
    FS_CLIENT_FILECLIENT_CC_BULKLOADER_CC, /* fs/client/fileclient/cc/bulkloader.cc */
    FS_CLIENT_FILECLIENT_CC_CLTEST_CC,    /* fs/client/fileclient/cc/cltest.cc */
    FS_CLIENT_FILECLIENT_CC_KVSPEC_CC,   /* fs/client/fileclient/cc/kvspec.cc */
    FS_CLIENT_FILECLIENT_CC_FIDCACHE_CC,    /* fs/client/fileclient/cc/fidcache.cc */
    FS_CLIENT_FILECLIENT_CC_CLIENT_CC,    /* fs/client/fileclient/cc/client.cc */
    FS_CLIENT_FILECLIENT_CC_DBCLIENT_CC,    /* fs/client/fileclient/cc/dbclient.cc */
    FS_CLIENT_FILECLIENT_CC_WRITEBUF_CC,    /* fs/client/fileclient/cc/writebuf.cc */
    FS_CLIENT_FILECLIENT_CC_LIBHDFS_API_CC, /* fs/client/fileclient/cc/libhdfs/api.cc */
    FS_CLIENT_FILECLIENT_CC_LIBHDFS_API_SUPPORT_CC,    /* fs/client/fileclient/cc/libhdfs/api_support.cc */
    FS_CLIENT_FILECLIENT_CC_LIBHDFS_FCCLUSTERCONF_CC,    /* fs/client/fileclient/cc/fcclusterconf.cc */
    FS_CLIENT_FILECLIENT_CC_SCANNER_CC,          /* fs/client/fileclient/cc/scanner.cc */
    FS_CLIENT_FILECLIENT_CC_PUTBUFFER_CC,        /* fs/client/fileclient/cc/putbuffer.cc */
    FS_CLIENT_FILECLIENT_CC_TABLETCACHE_CC,      /* fs/client/fileclient/cc/tabletcache.cc */
    FS_CLIENT_FILECLIENT_CC_WRITEQUEUE_CC,       /* fs/client/fileclient/cc/writequeue.cc */
    FS_COMMON_GTRACELEVEL_CC,    /* fs/common/gtracelevel.cc */
    FS_COMMON_LZF_CC,    /* fs/common/lzf.cc */
    FS_COMMON_FILEIDS_CC,    /* fs/common/fileids.cc */
    FS_COMMON_CACHEFILE_CC,    /* fs/common/cachefile.cc */
    FS_COMMON_COMPRESSION_CC,    /* fs/common/compression.cc */
    FS_COMMON_TRACE_CC,    /* fs/common/trace.cc */
    FS_COMMON_MODULES_CC,    /* fs/common/modules.cc */
    FS_COMMON_STATS_CC,    /* fs/common/stats.cc */
    FS_COMMON_GTRACE_CC,    /* fs/common/gtrace.cc */
    FS_COMMON_LICENSE_CC,   /* fs/common/license.cc */
    FS_RPC_HELLO_PB_CC,    /* fs/rpc/hello.pb.cc */
    FS_RPC_DISPATCH_CC,    /* fs/rpc/dispatch.cc */
    FS_RPC_SPEEDTEST_CC,    /* fs/rpc/speedtest.cc */
    FS_RPC_HELLOCLIENT_CC,    /* fs/rpc/helloclient.cc */
    FS_RPC_ONCSERVER_CC,    /* fs/rpc/oncserver.cc */
    FS_RPC_HELLOSERVER_CC,    /* fs/rpc/helloserver.cc */
    FS_RPC_LOCALRPC_CC,    /* fs/rpc/localrpc.cc */
    FS_RPC_THR_HELLOSERVER_CC,    /* fs/rpc/thr_helloserver.cc */
    FS_RPC_RPCBINDING_CC,    /* fs/rpc/rpcbinding.cc */
    FS_RPC_RPCTHR_CC,    /* fs/rpc/rpcthr.cc */
    FS_RPC_RPCSERVER_CC,    /* fs/rpc/rpcserver.cc */
    FS_RPC_HELLOINT_CC,    /* fs/rpc/helloint.cc */
    FS_RPC_RPCSERVER_SELECT_CC,    /* fs/rpc/rpcserver-select.cc */
    FS_RPC_THR_HELLOCLIENT_CC,    /* fs/rpc/thr_helloclient.cc */
    FS_RPC_RPCJNI_CC,    /* fs/rpc/rpcjni.cc */
    FS_RPC_RPCSERVER_EPOLL_CC,    /* fs/rpc/rpcserver-epoll.cc */
    FS_SERVER_CONTAINER_CREATE_CC,    /* fs/server/container/create.cc */
    FS_SERVER_CONTAINER_COW_CC,    /* fs/server/container/cow.cc */
    FS_SERVER_CONTAINER_CONTAINERUSAGE_CC,    /* fs/server/container/containerusage.cc */
    FS_SERVER_CONTAINER_VOLUMESNAP_CC,  /* fs/server/container/volumesnap.cc */
    FS_SERVER_CONTAINER_SNAPDC_CC,   /* fs/server/container/snapdc.cc */
    FS_SERVER_CONTAINER_SYNCUPTOVN_CC,    /* fs/server/container/syncuptovn.cc */
    FS_SERVER_CONTAINER_INODEMUTATOR_CC,    /* fs/server/container/inodemutator.cc */
    FS_SERVER_CONTAINER_SNAPSHOT_CC,    /* fs/server/container/snapshot.cc */
    FS_SERVER_CONTAINER_MAPPER_CC,    /* fs/server/container/mapper.cc */
    FS_SERVER_CONTAINER_READINODES_CC, /* fs/server/container/readinodes.cc */
    FS_SERVER_CONTAINER_DELETE_CC,    /* fs/server/container/delete.cc */
    FS_SERVER_CONTAINER_RENAME_CC,    /* fs/server/container/rename.cc */
    FS_SERVER_CONTAINER_CONTAINER_CC,    /* fs/server/container/container.cc */
    FS_SERVER_CONTAINER_ROLLBACK_CC,    /* fs/server/container/rollback.cc */
    FS_SERVER_CONTAINER_CONMETAINFOMUTATOR_CC,    /* fs/server/container/conmetainfomutator.cc */
    FS_SERVER_CONTAINER_CONTAINERREPORT_CC,    /* fs/server/container/containerreport.cc */
    FS_SERVER_CONTAINER_REPAIR_CC,    /* fs/server/container/repair.cc */
    FS_SERVER_BTREE_BTREELEAFITER_CC,    /* fs/server/btree/btreeleafiter.cc */
    FS_SERVER_BTREE_BTREEMGR_CC,    /* fs/server/btree/btreemgr.cc */
    FS_SERVER_BTREE_BTREESM_CC,    /* fs/server/btree/btreesm.cc */
    FS_SERVER_BTREE_BTREEAPIS_CC,    /* fs/server/btree/btreeapis.cc */
    FS_SERVER_BTREE_BTREENODE_CC,    /* fs/server/btree/btreenode.cc */
    FS_SERVER_BTREE_BTREEDELSCAN_CC,    /* fs/server/btree/btreedelscan.cc */
    FS_SERVER_BTREE_BTREEOWNERTRANSFER_CC,    /* fs/server/btree/btreeownertransfer.cc */
    FS_SERVER_TEST_THETEST_CC,    /* fs/server/test/thetest.cc */
    FS_SERVER_TEST_DIROPS_CC,    /* fs/server/test/dirops.cc */
    FS_SERVER_TEST_SNAP_CC,    /* fs/server/test/snap.cc */
    FS_SERVER_TEST_GETPATH_CC,    /* fs/server/test/getpath.cc */
    FS_SERVER_TEST_LOGTEST_CC,    /* fs/server/test/logtest.cc */
    FS_SERVER_TEST_INIT_CC,    /* fs/server/test/init.cc */
    FS_SERVER_TEST_RWTEST_CC,    /* fs/server/test/rwtest.cc */
    FS_SERVER_TEST_MFSPECK_CC,    /* fs/server/test/mfspeck.cc */
    FS_SERVER_TEST_SHARD_CC,    /* fs/server/test/shard.cc */
    FS_SERVER_TEST_DNLC_CC,    /* fs/server/test/dnlc.cc */
    FS_SERVER_TEST_RPCSHOOTER_WRITE_CC,    /* fs/server/test/rpcshooter/write.cc */
    FS_SERVER_TEST_RPCSHOOTER_READ_CC,    /* fs/server/test/rpcshooter/read.cc */
    FS_SERVER_TEST_RPCSHOOTER_NULLRPC_CC,    /* fs/server/test/rpcshooter/nullrpc.cc */
    FS_SERVER_TEST_RPCSHOOTER_OPSLIB_CC,    /* fs/server/test/rpcshooter/opslib.cc */
    FS_SERVER_TEST_RPCSHOOTER_OPS_CC,    /* fs/server/test/rpcshooter/ops.cc */
    FS_SERVER_TEST_BTREETEST_CC,    /* fs/server/test/btreetest.cc */
    FS_SERVER_TEST_CONTAINER_CC,    /* fs/server/test/container.cc */
    FS_SERVER_TEST_NFSPECK_CC,    /* fs/server/test/nfspeck.cc */
    FS_SERVER_TEST_LOGDUMP_CC,    /* fs/server/test/logdump.cc */
    FS_SERVER_TEST_FSPECK_CC,    /* fs/server/test/fspeck.cc */
    FS_SERVER_COMMON_HASHTABLE_CC,    /* fs/server/common/hashtable.cc */
    FS_SERVER_COMMON_SHELLSORT_CC,    /* fs/server/common/shellsort.cc */
    FS_SERVER_COMMON_INFOTABLE_CC,    /* fs/server/common/infotable.cc */
    FS_SERVER_COMMON_LOCK_CC,    /* fs/server/common/lock.cc */
    FS_SERVER_COMMON_IOVHANDLE_CC,    /* fs/server/common/iovhandle.cc */
    FS_SERVER_COMMON_CLDBHA_CC,    /* fs/server/common/cldbha.cc */
    FS_SERVER_COMMON_REPARENT_CC,    /* fs/server/common/reparent.cc */
    FS_SERVER_COMMON_CHAINIO_CC,    /* fs/server/common/chainio.cc */
    FS_SERVER_COMMON_CLISHM_CC,    /* fs/server/common/clishm.cc */
    FS_SERVER_ALLOCATOR_CLEANER_CC,    /* fs/server/allocator/cleaner.cc */
    FS_SERVER_ALLOCATOR_ALLOCATOR_CC,    /* fs/server/allocator/allocator.cc */
    FS_SERVER_ALLOCATOR_FREE_CC,    /* fs/server/allocator/free.cc */
    FS_SERVER_FSCK_PAGEINFO_CC,    /* fs/server/fsck/pageinfo.cc */
    FS_SERVER_FSCK_KEYVISIT_CC,    /* fs/server/fsck/keyvisit.cc */
    FS_SERVER_FSCK_BTREEWALK_CC,    /* fs/server/fsck/btreewalk.cc */
    FS_SERVER_FSCK_CLEANER_CC,    /* fs/server/fsck/cleaner.cc */
    FS_SERVER_FSCK_SPLOAD_CC,    /* fs/server/fsck/spload.cc */
    FS_SERVER_FSCK_STUBFN_CC,    /* fs/server/fsck/stubfn.cc */
    FS_SERVER_FSCK_MFSDB_CC,    /* fs/server/fsck/mfsdb.cc */
    FS_SERVER_FSCK_FILELOOKUP_CC,   /* fs/server/fsck/filelookup.cc */
    FS_SERVER_FSCK_BTREELOOKUP_CC,   /* fs/server/fsck/btreelookup.cc */
    FS_SERVER_FSCK_FILEREAD_CC,  /* fs/server/fsck/fileread.cc */
    FS_SERVER_FSCK_LAYOUT_CC,    /* fs/server/fsck/layout.cc */
    FS_SERVER_FSCK_INIT_CC,    /* fs/server/fsck/init.cc */
    FS_SERVER_FSCK_FSCK_CC,    /* fs/server/fsck/fsck.cc */
    FS_SERVER_FSCK_REPAIR_CC,    /* fs/server/fsck/repair.cc */
    FS_SERVER_FSCK_READAHEAD_CC,    /* fs/server/fsck/readahead.cc */
    FS_SERVER_FSCK_CIDMAP_CC,    /* fs/server/fsck/cidmap.cc */
    FS_SERVER_FSCK_ALLOC_CC,    /* fs/server/fsck/alloc.cc */
    FS_SERVER_FSCK_PHASE1_CC,    /* fs/server/fsck/phase1.cc */
    FS_SERVER_FSCK_PHASE2_CC,    /* fs/server/fsck/phase2.cc */
    FS_SERVER_FSCK_PHASE3_CC,    /* fs/server/fsck/phase3.cc */
    FS_SERVER_FSCK_PHASE4_CC,    /* fs/server/fsck/phase4.cc */
    FS_SERVER_FSCK_PHASE5_CC,    /* fs/server/fsck/phase5.cc */
    FS_SERVER_FSCK_PHASE6FILE_CC, /* fs/server/fsck/phase6file.cc */
    FS_SERVER_FSCK_PHASE6_CC,    /* fs/server/fsck/phase6.cc */
    FS_SERVER_CACHE_CACHEMGR_CC,    /* fs/server/cache/cachemgr.cc */
    FS_SERVER_REPLICATION_ORPHANLISTRESTORE_CC,    /* fs/server/replication/orphanlistrestore.cc */
    FS_SERVER_REPLICATION_VOLUMEMIRROR_CC,    /* fs/server/replication/volumemirror.cc */
    FS_SERVER_REPLICATION_REPLICATEOPS_CC,    /* fs/server/replication/replicateops.cc */
    FS_SERVER_REPLICATION_DUMPFILE_CC,    /* fs/server/replication/dumpfile.cc */
    FS_SERVER_REPLICATION_IDLERESYNCCHECKER_CC,    /* fs/server/replication/idleresyncchecker.cc */
    FS_SERVER_REPLICATION_NODEFAILURE_CC,    /* fs/server/replication/nodefailure.cc */
    FS_SERVER_REPLICATION_CONTAINERLIST_CC,    /* fs/server/replication/containerlist.cc */
    FS_SERVER_REPLICATION_TABLERESYNCBUF_CC,    /* fs/server/replication/tableresyncbuf.cc */
    FS_SERVER_REPLICATION_INODERESTORE_CC,    /* fs/server/replication/inoderestore.cc */
    FS_SERVER_REPLICATION_CONTAINERRESTORE_CC,    /* fs/server/replication/containerrestore.cc */
    FS_SERVER_REPLICATION_DUMPCMP_CC,    /* fs/server/replication/dumpcmp.cc */
    FS_SERVER_REPLICATION_EXTRACTFID_CC,    /* fs/server/replication/extractfid.cc */
    FS_SERVER_REPLICATION_FIRSTWRITE_CC,    /* fs/server/replication/firstwrite.cc */
    FS_SERVER_REPLICATION_INODEITERRANGEBUF_CC,    /* fs/server/replication/inodeiterrangebuf.cc */
    FS_SERVER_REPLICATION_TESTTXN_CC,    /* fs/server/replication/testtxn.cc */
    FS_SERVER_REPLICATION_CHAIN_CC,    /* fs/server/replication/chain.cc */
    FS_SERVER_REPLICATION_RPCBINDINGSCACHE_CC,    /* fs/server/replication/rpcbindingscache.cc */
    FS_SERVER_REPLICATION_WRITEBUCKETMGR_CC,    /* fs/server/replication/writebucketmgr.cc */
    FS_SERVER_REPLICATION_CONTAINERRESYNC_CC,    /* fs/server/replication/containerresync.cc */
    FS_SERVER_REPLICATION_CONTAINERRESYNCFROMSNAPSHOT_CC,    /* fs/server/replication/containerresyncfromsnapshot.cc */
    FS_SERVER_REPLICATION_INODEITERATOR_CC,    /* fs/server/replication/inodeiterator.cc */
    FS_SERVER_REPLICATION_CONTAINERINFO_CC,    /* fs/server/replication/containerinfo.cc */
    FS_SERVER_REPLICATION_REPLCHAIN_CC,    /* fs/server/replication/replchain.cc */
    FS_SERVER_REPLICATION_REPLCLIENT_CC,    /* fs/server/replication/replclient.cc */
    FS_SERVER_REPLICATION_VERSIONNUMBERS_CC,    /* fs/server/replication/versionnumbers.cc */
    FS_SERVER_REPLICATION_RESYNCABORT_CC,    /* fs/server/replication/resyncabort.cc */
    FS_SERVER_REPLICATION_ATTRTEST_CC,    /* fs/server/replication/attrtest.cc */
    FS_SERVER_REPLICATION_DIRTYINODES_CC,    /* fs/server/replication/dirtyinodes.cc */
    FS_SERVER_REPLICATION_RESYNCRECORDITERATORS_CC,    /* fs/server/replication/resyncrecorditerators.cc */
    FS_SERVER_REPLICATION_REPLICAINFO_CC,    /* fs/server/replication/replicainfo.cc */
    FS_SERVER_REPLICATION_BUCKETMGR_CC,    /* fs/server/replication/bucketmgr.cc */
    FS_SERVER_REPLICATION_CONTAINERREPLAY_CC,    /* fs/server/replication/containerreplay.cc */
    FS_SERVER_REPLICATION_REPLICATIONSERVER_CC,    /* fs/server/replication/replicationserver.cc */
    FS_SERVER_REPLICATION_VOLUMEMIRRORSERVER_CC,    /* fs/server/replication/volumemirrorserver.cc */
    FS_SERVER_REPLICATION_CONTAINERROLLBACK_CC,    /* fs/server/replication/containerrollback.cc */
    FS_SERVER_REPLICATION_CONTAINERUNDO_CC,    /* fs/server/replication/containerundo.cc */
    FS_SERVER_REPLICATION_RESYNCPROC_CC,    /* fs/server/replication/resyncproc.cc */
    FS_SERVER_REPLICATION_FILERESTORE_CC,    /* fs/server/replication/filerestore.cc */
    FS_SERVER_REPLICATION_CLIENT_CC,    /* fs/server/replication/client.cc */
    FS_SERVER_REPLICATION_INODERESYNC_CC,    /* fs/server/replication/inoderesync.cc */
    FS_SERVER_REPLICATION_REPLICATE_CC,    /* fs/server/replication/replicate.cc */
    FS_SERVER_REPLICATION_TABLERESTORE_CC,    /* fs/server/replication/tablerestore.cc */
    FS_SERVER_REPLICATION_RESYNCWORKAREAS_CC,    /* fs/server/replication/resyncworkareas.cc */
    FS_SERVER_REPLICATION_MYTEST_CC,    /* fs/server/replication/mytest.cc */
    FS_SERVER_REPLICATION_VOLUMECREATEDUMP_CC,    /* fs/server/replication/volumecreatedump.cc */
    FS_SERVER_REPLICATION_VOLUMERESTOREDUMP_CC,    /* fs/server/replication/volumerestoredump.cc */
    FS_SERVER_REPLICATION_CLDBBINDING_CC,    /* fs/server/replication/cldbbinding.cc */
    FS_SERVER_REPLICATION_CONTAINERBINDING_CC,    /* fs/server/replication/containerbinding.cc */
    FS_SERVER_REPLICATION_DUMPCLIENT_CC,    /* fs/server/replication/dumpclient.cc */
    FS_SERVER_REPLICATION_VOLUMEDUMPREAD_CC,    /* fs/server/replication/volumedumpread.cc */
    FS_SERVER_REPLICATION_VOLUMEDUMPPRINT_CC,    /* fs/server/replication/volumedumpprint.cc */
    FS_SERVER_UTIL_CHECKDATALOSS_CC,    /* fs/server/util/checkdataloss.cc */
    FS_SERVER_UTIL_HOSTSTATS_CC,    /* fs/server/util/hoststats.cc */
    FS_SERVER_UTIL_SPTEST_CC,    /* fs/server/util/sptest.cc */
    FS_SERVER_UTIL_GUTS_CC,    /* fs/server/util/guts.cc */
    FS_SERVER_UTIL_MRCONFIG_CC,    /* fs/server/util/mrconfig.cc */
    FS_SERVER_CLEANER_CLEANER_CC,    /* fs/server/cleaner/cleaner.cc */
    FS_SERVER_CLEANER_BCLEANER_CC,    /* fs/server/cleaner/bcleaner.cc */
    FS_SERVER_CLEANER_ICLEANER_CC,    /* fs/server/cleaner/icleaner.cc */
    FS_SERVER_CLEANER_IBIN_CC,    /* fs/server/cleaner/ibin.cc */
    FS_SERVER_CLEANER_DCLEANER_CC,    /* fs/server/cleaner/dcleaner.cc */
    FS_SERVER_CLEANER_DCLEANER_SM_CC,    /* fs/server/cleaner/dcleaner-sm.cc */
    FS_SERVER_PCLDB_PCLDB_CC,    /* fs/server/pcldb/pcldb.cc */
    FS_SERVER_PCLDB_VOLCLIENT_CC,    /* fs/server/pcldb/volclient.cc */
    FS_SERVER_ORPHANAGE_ORPHANAGE_CC,    /* fs/server/orphanage/orphanage.cc */
    FS_SERVER_TRANS_TRANS_CC,    /* fs/server/trans/trans.cc */
    FS_SERVER_IO_SPSERVER_CC,    /* fs/server/io/spserver.cc */
    FS_SERVER_IO_IODISPATCH_CC,    /* fs/server/io/iodispatch.cc */
    FS_SERVER_IO_SPALIAS_CC,    /* fs/server/io/spalias.cc */
    FS_SERVER_IO_CONFIGSP_CC,    /* fs/server/io/configsp.cc */
    FS_SERVER_IO_CONFIGLOG_CC,    /* fs/server/io/configlog.cc */
    FS_SERVER_IO_CONFIGDG_CC,    /* fs/server/io/configdg.cc */
    FS_SERVER_IO_SPUPDATE_CC,    /* fs/server/io/spupdate.cc */
    FS_SERVER_IO_IOMGR_CC,    /* fs/server/io/iomgr.cc */
    FS_SERVER_IO_SP_CC,    /* fs/server/io/sp.cc */
    FS_SERVER_IO_LUN_CC,    /* fs/server/io/lun.cc */
    FS_SERVER_IO_SPINIT_CC,    /* fs/server/io/spinit.cc */
    FS_SERVER_IO_LOADCIDMAP_CC,    /* fs/server/io/loadcidmap.cc */
    FS_SERVER_IO_CONFIG_CC,    /* fs/server/io/config.cc */
    FS_SERVER_IO_DAMAGEDVOLS_CC,    /* fs/server/io/damagedvols.cc */
    FS_SERVER_MAPSERVER_READDIR_CC,    /* fs/server/mapserver/readdir.cc */
    FS_SERVER_MAPSERVER_MOVEDANGLING_CC, /* fs/server/mapserver/movedangling.cc */
    FS_SERVER_MAPSERVER_CREATE_CC,    /* fs/server/mapserver/create.cc */
    FS_SERVER_MAPSERVER_SERVERINFO_CC,    /* fs/server/mapserver/serverinfo.cc */
    FS_SERVER_MAPSERVER_PUNCHHOLE_CC,    /* fs/server/mapserver/punchhole.cc */
    FS_SERVER_MAPSERVER_READAHEADBUF_CC,    /* fs/server/mapserver/readaheadbuf.cc */
    FS_SERVER_MAPSERVER_FILEPREFETCH_CC,    /* fs/server/mapserver/fileprefetch.cc */
    FS_SERVER_MAPSERVER_FILESERVER_CC,    /* fs/server/mapserver/fileserver.cc */
    FS_SERVER_MAPSERVER_PROCQUEUE_H,    /* fs/server/mapserver/procqueue.h */
    FS_SERVER_MAPSERVER_WRITE_APPLYDATA_CC,    /* fs/server/mapserver/write/applydata.cc */
    FS_SERVER_MAPSERVER_WRITE_COMPRESSANDPACK_CC,    /* fs/server/mapserver/write/compressandpack.cc */
    FS_SERVER_MAPSERVER_SECUREDATA_CC, /* fs/server/mapserver/securedata.cc */
    FS_SERVER_MAPSERVER_WRITE_INSERTCLSTDESC_CC,    /* fs/server/mapserver/write/insertclstdesc.cc */
    FS_SERVER_MAPSERVER_WRITE_LOOKUPANDPOPULATE_CC,    /* fs/server/mapserver/write/lookupandpopulate.cc */
    FS_SERVER_MAPSERVER_WRITE_CHKPERMS_CC,    /* fs/server/mapserver/write/chkperms.cc */
    FS_SERVER_MAPSERVER_WRITE_WRITEFILE_CC,   /* fs/server/mapserver/write/writefile.cc */
    FS_SERVER_MAPSERVER_WRITE_GETDATA_CC,     /* fs/server/mapserver/write/getdata.cc */
    FS_SERVER_MAPSERVER_WRITE_WRITEV3_CC,     /* fs/server/mapserver/write/writev3.cc */
    FS_SERVER_MAPSERVER_WRITE_PREPARECD_CC,   /* fs/server/mapserver/write/preparecd.cc */
    FS_SERVER_MAPSERVER_WRITE_CLIST_CC,       /* fs/server/mapserver/write/clist.cc */
    FS_SERVER_MAPSERVER_WRITE_DISPOSE_CC,     /* fs/server/mapserver/write/dispose.cc */
    FS_SERVER_MAPSERVER_WRITE_PACK_CC,        /* fs/server/mapserver/write/pack.cc */
    FS_SERVER_MAPSERVER_WRITE_UNPACK_CC,      /* fs/server/mapserver/write/unpack.cc */
    FS_SERVER_MAPSERVER_WRITE_UTIL_CC,        /* fs/server/mapserver/write/util.cc */
    FS_SERVER_MAPSERVER_WRITE_UNCOMPRESS_CC,  /* fs/server/mapserver/write/uncompress.cc */
    FS_SERVER_MAPSERVER_WRITE_WPAGE_CC,       /* fs/server/mapserver/write/wpage.cc */
    FS_SERVER_MAPSERVER_WRITE_APPLY_CC,       /* fs/server/mapserver/write/apply.cc */
    FS_SERVER_MAPSERVER_WRITE_META_CC,        /* fs/server/mapserver/write/meta.cc */
    FS_SERVER_MAPSERVER_KVSTORERANGEDELETE_CC,    /* fs/server/mapserver/kvstorerangedelete.cc */
    FS_SERVER_MAPSERVER_BULKINSERT_CC,     /* fs/server/mapserver/bulkinsert.cc*/
    FS_SERVER_MAPSERVER_KVSTOREMULTIOPDB_CC,    /* fs/server/mapserver/kvstoremultiopdb.cc*/
    FS_SERVER_MAPSERVER_WRITE_CC,    /* fs/server/mapserver/write.cc */
    FS_SERVER_MAPSERVER_GETFILELETATTR_CC,    /* fs/server/mapserver/getfileletattr.cc */
    FS_SERVER_MAPSERVER_ATTR_CC,    /* fs/server/mapserver/attr.cc */
    FS_SERVER_MAPSERVER_SYNCFILE_CC,    /* fs/server/mapserver/syncfile.cc */
    FS_SERVER_MAPSERVER_SYNCCONFIRM_CC,    /* fs/server/mapserver/syncconfirm.cc */
    FS_SERVER_MAPSERVER_ADVISE_CC,    /* fs/server/mapserver/advise.cc */
    FS_SERVER_MAPSERVER_REPAIRFIDMAP_CC,    /* fs/server/mapserver/repairfidmap.cc */
    FS_SERVER_MAPSERVER_ALLOCATEFID_CC,    /* fs/server/mapserver/allocatefid.cc */
    FS_SERVER_MAPSERVER_GETFIDMAP_CC,    /* fs/server/mapserver/getfidmap.cc */
    FS_SERVER_MAPSERVER_GETINODES_CC,    /* fs/server/mapserver/getinodes.cc */
    FS_SERVER_MAPSERVER_CIDCACHE_CC,    /* fs/server/mapserver/cidcache.cc */
    FS_SERVER_MAPSERVER_READAHEAD_CC,    /* fs/server/mapserver/readahead.cc */
    FS_SERVER_MAPSERVER_DEFER_CC,    /* fs/server/mapserver/defer.cc */
    FS_SERVER_MAPSERVER_CTABLE_CC,    /* fs/server/mapserver/ctable.cc */
    FS_SERVER_MAPSERVER_READ_CC,    /* fs/server/mapserver/read.cc */
    FS_SERVER_MAPSERVER_READV3_CC,    /* fs/server/mapserver/readv3.cc */
    FS_SERVER_MAPSERVER_RESYNCREAD_CC,    /* fs/server/mapserver/resyncread.cc */
    FS_SERVER_MAPSERVER_READCOPYOUT_CC,    /* fs/server/mapserver/readcopyout.cc */
    FS_SERVER_MAPSERVER_READCLUSTER_CC,    /* fs/server/mapserver/readcluster.cc */
    FS_SERVER_MAPSERVER_READDIRBUF_CC,    /* fs/server/mapserver/readdirbuf.cc */
    FS_SERVER_MAPSERVER_REMOTEFS_CC,    /* fs/server/mapserver/remotefs.cc */
    FS_SERVER_MAPSERVER_REQUESTHANDLE_CC,    /* fs/server/mapserver/requesthandle.cc */
    FS_SERVER_MAPSERVER_TRUNCTREE_CC,    /* fs/server/mapserver/trunctree.cc */
    FS_SERVER_MAPSERVER_LOOKUP_CC,    /* fs/server/mapserver/lookup.cc */
    FS_SERVER_MAPSERVER_GETPATH_CC,    /* fs/server/mapserver/getpath.cc */
    FS_SERVER_MAPSERVER_LOCKS_CC,    /* fs/server/mapserver/locks.cc */
    FS_SERVER_MAPSERVER_KVSTOREGETKEY_CC,    /* fs/server/mapserver/kvstoregetkey.cc */
    FS_SERVER_MAPSERVER_SHARD_CC,    /* fs/server/mapserver/shard.cc */
    FS_SERVER_MAPSERVER_VOLUME_CC,    /* fs/server/mapserver/volume.cc */
    FS_SERVER_MAPSERVER_MAPSERVER_CC,    /* fs/server/mapserver/mapserver.cc */
    FS_SERVER_MAPSERVER_PURGEFIDMAP_CC,    /* fs/server/mapserver/purgefidmap.cc */
    FS_SERVER_MAPSERVER_SYMLINK_CC,    /* fs/server/mapserver/symlink.cc */
    FS_SERVER_MAPSERVER_XTRUNCATE_CC,    /* fs/server/mapserver/xtruncate.cc */
    FS_SERVER_MAPSERVER_GETWRITEDATA_CC,    /* fs/server/mapserver/getwritedata.cc */
    FS_SERVER_MAPSERVER_WORKAREAS_CC,    /* fs/server/mapserver/workareas.cc */
    FS_SERVER_MAPSERVER_PROCQUEUE_CC,    /* fs/server/mapserver/procqueue.cc */
    FS_SERVER_MAPSERVER_SERVERCOMMAND_CC,    /* fs/server/mapserver/servercommand.cc */
    FS_SERVER_MAPSERVER_MAPFS_CC,    /* fs/server/mapserver/mapfs.cc */
    FS_SERVER_MAPSERVER_LOADSP_CC,    /* fs/server/mapserver/loadsp.cc */
    FS_SERVER_MAPSERVER_READAHEADMGR_CC,    /* fs/server/mapserver/readaheadmgr.cc */
    FS_SERVER_MAPSERVER_TRUNCATE_CC,    /* fs/server/mapserver/truncate.cc */
    FS_SERVER_MAPSERVER_KVSTORESCAN_CC,    /* fs/server/mapserver/kvstorescan.cc */
    FS_SERVER_MAPSERVER_FILERA_CC,    /* fs/server/mapserver/filera.cc */
    FS_SERVER_MAPSERVER_DIRCONNECT_CC,  /* fs/server/mapserver/dirconnect.cc */
    FS_SERVER_MAPSERVER_RENAME_CC,    /* fs/server/mapserver/rename.cc */
    FS_SERVER_MAPSERVER_CLUSTERDECOMPRESS_CC,    /* fs/server/mapserver/clusterdecompress.cc */
    FS_SERVER_MAPSERVER_VALIDATERPC_CC,    /* fs/server/mapserver/validaterpc.cc */
    FS_SERVER_MAPSERVER_UNLINK_CC,    /* fs/server/mapserver/unlink.cc */
    FS_SERVER_MAPSERVER_KVSTORELOOKUP_CC,    /* fs/server/mapserver/kvstorelookup.cc */
    FS_SERVER_MAPSERVER_RWCOMMON_CC,    /* fs/server/mapserver/rwcommon.cc */
    FS_SERVER_MAPSERVER_SETFILELETSZ_CC,    /* fs/server/mapserver/setfileletsz.cc */
    FS_SERVER_MAPSERVER_DIRHASHENT_CC,    /* fs/server/mapserver/dirhashent.cc */
    FS_SERVER_MAPSERVER_KVSTOREMULTIOP_CC,    /* fs/server/mapserver/kvstoremultiop.cc */
    FS_SERVER_MAPSERVER_PERMISSIONS_CC,    /* fs/server/mapserver/permissions.cc */
    FS_SERVER_MAPSERVER_TRANSFERCOUNT_CC,  /* fs/server/mapserver/transfercount.cc */
    FS_SERVER_MAPSERVER_RECURSERM_CC, /* fs/server/mapserver/recurserm.cc */
    FS_SERVER_MAPSERVER_DNLC_CC,    /* fs/server/mapserver/dnlc.cc */
    FS_SERVER_MAPSERVER_ASSIGNFORTABLET_CC, /* fs/server/mapserver/assignfortablet.cc */
    FS_SERVER_MAPSERVER_DBCALLS_CC, /* fs/server/mapserver/dbcalls.cc */
    FS_SERVER_MAPSERVER_SCANCF_CC, /* fs/server/mapserver/scancf.cc*/
    FS_SERVER_DBDELETE_DELSCANNER_CC, /* fs/server/mapserver/dbdelete/delscanner.cc */
    FS_SERVER_DBDELETE_SEGMAPDELSCANNER_CC, /* fs/server/mapserver/dbdelete/segmapdelscanner.cc */
    FS_SERVER_DBDELETE_SPILLMAPDELSCANNER_CC, /* fs/server/mapserver/dbdelete/spillmapdelscanner.cc */
    FS_SERVER_DBDELETE_TABLEDELSCANNER_CC, /* fs/server/mapserver/dbdelete/tabledelscanner.cc */
    FS_SERVER_DBDELETE_TABLETDELSCANNER_CC, /* fs/server/mapserver/dbdelete/tabletdelscanner.cc */
    FS_SERVER_DBDELETE_TABLETMAPDELSCANNER_CC, /* fs/server/mapserver/dbdelete/tabletmapdelscanner.cc */
    FS_SERVER_DBCHECK_TABLETRANGECHECK_CC, /* fs/server/mapserver/dbcheck/tabletrangecheck.cc */
    FS_SERVER_DBCHECK_KEYMAPSCAN_CC, /* fs/server/mapserver/dbcheck/keymapscan.cc */
    FS_SERVER_MAPSERVER_TEST_TESTCASE_CC, /* fs/server/mapserver/test/testcase.cc */
    FS_SERVER_LOG_MAIN_CC,    /* fs/server/log/main.cc */
    FS_SERVER_LOG_RECOVERY_CC,    /* fs/server/log/recovery.cc */
    FS_SERVER_LOG_PAGE_CC,    /* fs/server/log/page.cc */
    FS_SERVER_LOG_PAGEIO_CC,    /* fs/server/log/pageio.cc */
    FS_SERVER_LOG_MFSLOG_CC,    /* fs/server/log/mfslog.cc */
    FS_SERVER_LOG_LOG_CC,    /* fs/server/log/log.cc */
    FS_SERVER_LOG_RECORDS_CC,    /* fs/server/log/records.cc */
    FS_SERVER_LOG_TXN_CC,    /* fs/server/log/txn.cc */
    FS_NFSD_TEST_RANDWRITE_CC,    /* fs/nfsd/test/randwrite.cc */
    FS_NFSD_TEST_NFSHANDLE_CC,    /* fs/nfsd/test/nfshandle.cc */
    FS_NFSD_TEST_WRITE_CC,    /* fs/nfsd/test/write.cc */
    FS_NFSD_TEST_RANDREAD_CC,    /* fs/nfsd/test/randread.cc */
    FS_NFSD_NFSCOMMON_CC,    /* fs/nfsd/nfscommon.cc */
    FS_NFSD_ATTRS_CC,    /* fs/nfsd/attrs.cc */
    FS_NFSD_MAIN_CC,    /* fs/nfsd/main.cc */
    FS_NFSD_CACHE_CC,    /* fs/nfsd/cache.cc */
    FS_NFSD_UTILS_CC,    /* fs/nfsd/utils.cc */
    FS_NFSD_REQUESTHANDLE_CC,    /* fs/nfsd/requesthandle.cc */
    FS_NFSD_FILEOPS_CC,    /* fs/nfsd/fileops.cc */
    FS_NFSD_MOUNT_CC,    /* fs/nfsd/mount.cc */
    FS_NFSD_LOG_CC,    /* fs/nfsd/log.cc */
    FS_NFSD_NFSSERVER_CC,    /* fs/nfsd/nfsserver.cc */
    FS_NFSD_SHMEM_CC,   /* fs/nfsd/shmem.cc */
    FS_NFSD_DIR_CC,    /* fs/nfsd/dir.cc */
    FS_NFSD_CONFIG_CC,    /* fs/nfsd/config.cc */
    FS_NFSD_NFSHA_CC,    /* fs/nfsd/nfsha.cc */
    FS_NFSD_NFSMON_CC,    /* fs/nfsd/nfsmon.cc */
    FS_CLIENT_FILECLIENT_CC_FIDCACHE_H,    /* fs/client/fileclient/cc/fidcache.h */
    FS_CLIENT_FILECLIENT_CC_JNI_LOCAL_H,    /* fs/client/fileclient/cc/jni_local.h */
    FS_CLIENT_FILECLIENT_CC_INODE_H,    /* fs/client/fileclient/cc/inode.h */
    FS_CLIENT_FILECLIENT_CC_CIDCACHE_H,    /* fs/client/fileclient/cc/cidcache.h */
    FS_CLIENT_FILECLIENT_CC_COM_MAPR_KVSTORE_KVSTORECLIENT_H,    /* fs/client/fileclient/cc/com_mapr_kvstore_KvStoreClient.h */
    FS_CLIENT_FILECLIENT_CC_SHMEM_H,    /* fs/client/fileclient/cc/shmem.h */
    FS_CLIENT_FILECLIENT_CC_TABLE_H,    /* fs/client/fileclient/cc/table.h */
    FS_CLIENT_FILECLIENT_CC_CLIENT_H,    /* fs/client/fileclient/cc/client.h */
    FS_CLIENT_FILECLIENT_CC_COMMON_H,    /* fs/client/fileclient/cc/common.h */
    FS_CLIENT_FILECLIENT_CC_FIDMAP_H,    /* fs/client/fileclient/cc/fidmap.h */
    FS_CLIENT_FILECLIENT_CC_FILEOPS_H,    /* fs/client/fileclient/cc/fileops.h */
    FS_COMMON_TRACE_H,    /* fs/common/trace.h */
    FS_COMMON_GTRACE_H,    /* fs/common/gtrace.h */
    FS_COMMON_COMPRESSION_H,    /* fs/common/compression.h */
    FS_COMMON_DEBUGINFO_H,    /* fs/common/debuginfo.h */
    FS_COMMON_MODULES_H,    /* fs/common/modules.h */
    FS_COMMON_STATS_H,    /* fs/common/stats.h */
    FS_COMMON_LZF_H,    /* fs/common/lzf.h */
    FS_COMMON_ERRNO_H,    /* fs/common/errno.h */
    FS_COMMON_GTRACELEVEL_H,    /* fs/common/gtracelevel.h */
    FS_COMMON_FILEIDS_H,    /* fs/common/fileids.h */
    FS_COMMON_COMMON_H,    /* fs/common/common.h */
    FS_COMMON_GTRACEPROGRAM_H,    /* fs/common/gtraceprogram.h */
    FS_COMMON_LICENSE_H,  /* fs/common/license.h */
    FS_RPC_SIMP_H,    /* fs/rpc/simp.h */
    FS_RPC_RPCPROGRAM_H,    /* fs/rpc/rpcprogram.h */
    FS_RPC_RPCTHR_H,    /* fs/rpc/rpcthr.h */
    FS_RPC_SIMPCLIENT_C,    /* fs/rpc/simpclient.c */
    FS_RPC_RPCSERVER_H,    /* fs/rpc/rpcserver.h */
    FS_RPC_SIMP_SVC_C,    /* fs/rpc/simp_svc.c */
    FS_RPC_SIMP_CLNT_C,    /* fs/rpc/simp_clnt.c */
    FS_RPC_SIMP_XDR_C,    /* fs/rpc/simp_xdr.c */
    FS_RPC_JAVA_COM_MAPR_FS_RPC_H,    /* fs/rpc/java/com_mapr_fs_Rpc.h */
    FS_RPC_RPCBINDING_H,    /* fs/rpc/rpcbinding.h */
    FS_RPC_RPCCALLCONTEXT_H,    /* fs/rpc/rpccallcontext.h */
    FS_RPC_RPCWORKAREA_H,    /* fs/rpc/rpcworkarea.h */
    FS_RPC_DISPATCH_H,    /* fs/rpc/dispatch.h */
    FS_RPC_HELLO_PB_H,    /* fs/rpc/hello.pb.h */
    FS_SERVER_CONTAINER_UTILWA_H,    /* fs/server/container/utilwa.h */
    FS_SERVER_CONTAINER_INODEMUTATOR_H,    /* fs/server/container/inodemutator.h */
    FS_SERVER_CONTAINER_UPDATEWA_H,    /* fs/server/container/updatewa.h */
    FS_SERVER_CONTAINER_CONMETAINFOMUTATOR_H,    /* fs/server/container/conmetainfomutator.h */
    FS_SERVER_CONTAINER_CONTAINERFLUSHWA_H,    /* fs/server/container/containerflushwa.h */
    FS_SERVER_CONTAINER_INODE_H,    /* fs/server/container/inode.h */
    FS_SERVER_CONTAINER_MAPINODEWA_H,    /* fs/server/container/mapinodewa.h */
    FS_SERVER_CONTAINER_CONTAINER_H,    /* fs/server/container/container.h */
    FS_SERVER_CONTAINER_SNAPSHOTCREATEWA_H,    /* fs/server/container/snapshotcreatewa.h */
    FS_SERVER_CONTAINER_CONTAINERWA_H,    /* fs/server/container/containerwa.h */
    FS_SERVER_CONTAINER_ILISTCOWRANGEBUF_H,    /* fs/server/container/ilistcowrangebuf.h */
    FS_SERVER_CONTAINER_DELETEWA_H,    /* fs/server/container/deletewa.h */
    FS_SERVER_CONTAINER_MAPBLOCKWA_H,    /* fs/server/container/mapblockwa.h */
    FS_SERVER_CONTAINER_CIDMAP_H,    /* fs/server/container/cidmap.h */
    FS_SERVER_CONTAINER_CONTAINERUSAGEWA_H,    /* fs/server/container/containerusagewa.h */
    FS_SERVER_CONTAINER_TEMPLATEPGWA_H,    /* fs/server/container/templatepgwa.h */
    FS_SERVER_CONTAINER_CREATEWA_H,    /* fs/server/container/createwa.h */
    FS_SERVER_CONTAINER_CONTAINERUSAGE_H,    /* fs/server/container/containerusage.h */
    FS_SERVER_CONTAINER_CONMETAINFOWA_H,    /* fs/server/container/conmetainfowa.h */
    FS_SERVER_CONTAINER_CONTAINERREPORT_H,    /* fs/server/container/containerreport.h */
    FS_SERVER_BTREE_BTREELEAFITER_H,    /* fs/server/btree/btreeleafiter.h */
    FS_SERVER_BTREE_BTREEWA_H,    /* fs/server/btree/btreewa.h */
    FS_SERVER_BTREE_BTREEOWNERTRANSFER_H,    /* fs/server/btree/btreeownertransfer.h */
    FS_SERVER_BTREE_BTREEDELSCAN_H,    /* fs/server/btree/btreedelscan.h */
    FS_SERVER_BTREE_BTREEOWNERTRANSFERWA_H,    /* fs/server/btree/btreeownertransferwa.h */
    FS_SERVER_BTREE_BTREENODE_H,    /* fs/server/btree/btreenode.h */
    FS_SERVER_BTREE_BTREE_H,    /* fs/server/btree/btree.h */
    FS_SERVER_BTREE_BTREEMGR_H,    /* fs/server/btree/btreemgr.h */
    FS_SERVER_TEST_MFSPECK_H,    /* fs/server/test/mfspeck.h */
    FS_SERVER_TEST_THETEST_H,    /* fs/server/test/thetest.h */
    FS_SERVER_TEST_FSPECK_H,    /* fs/server/test/fspeck.h */
    FS_SERVER_TEST_RPCSHOOTER_OPS_H,    /* fs/server/test/rpcshooter/ops.h */
    FS_SERVER_TEST_DIRLIST_H,    /* fs/server/test/dirlist.h */
    FS_SERVER_COMMON_CHAINIO_H,    /* fs/server/common/chainio.h */
    FS_SERVER_COMMON_CLDBHA_H,    /* fs/server/common/cldbha.h */
    FS_SERVER_COMMON_CLDBHAWA_H,    /* fs/server/common/cldbhawa.h */
    FS_SERVER_COMMON_REPARENT_H,    /* fs/server/common/reparent.h */
    FS_SERVER_COMMON_LOCKWA_H,    /* fs/server/common/lockwa.h */
    FS_SERVER_COMMON_SHELLSORT_H,    /* fs/server/common/shellsort.h */
    FS_SERVER_COMMON_HASHTABLE_H,    /* fs/server/common/hashtable.h */
    FS_SERVER_COMMON_XORCRC32_H,    /* fs/server/common/xorcrc32.h */
    FS_SERVER_COMMON_INFOTABLE_H,    /* fs/server/common/infotable.h */
    FS_SERVER_COMMON_ALLOCFREE_H,    /* fs/server/common/allocfree.h */
    FS_SERVER_COMMON_LOCK_H,    /* fs/server/common/lock.h */
    FS_SERVER_COMMON_MAPFS_H,    /* fs/server/common/mapfs.h */
    FS_SERVER_COMMON_BITMAP_H,    /* fs/server/common/bitmap.h */
    FS_SERVER_COMMON_CLISHM_H,    /* fs/server/common/clishm.h */
    FS_SERVER_COMMON_BITMAP_INLINE_H,    /* fs/server/common/bitmap.inline.h */
    FS_SERVER_COMMON_WAITQ_H,    /* fs/server/common/waitq.h */
    FS_SERVER_COMMON_IOVHANDLE_H,    /* fs/server/common/iovhandle.h */
    FS_SERVER_ALLOCATOR_VECTOR_H,    /* fs/server/allocator/vector.h */
    FS_SERVER_ALLOCATOR_ALLOCWA_H,    /* fs/server/allocator/allocwa.h */
    FS_SERVER_ALLOCATOR_ALLOCATOR_H,    /* fs/server/allocator/allocator.h */
    FS_SERVER_FSCK_KEYVISIT_H,    /* fs/server/fsck/keyvisit.h */
    FS_SERVER_FSCK_BTREEWALK_H,    /* fs/server/fsck/btreewalk.h */
    FS_SERVER_FSCK_ALLOC_H,    /* fs/server/fsck/alloc.h */
    FS_SERVER_FSCK_FSCK_H,    /* fs/server/fsck/fsck.h */
    FS_SERVER_FSCK_CIDMAP_H,    /* fs/server/fsck/cidmap.h */
    FS_SERVER_FSCK_FSCKWA_H,    /* fs/server/fsck/fsckwa.h */
    FS_SERVER_FSCK_READAHEAD_H,    /* fs/server/fsck/readahead.h */
    FS_SERVER_CACHE_CACHEIRWA_H,    /* fs/server/cache/cacheirwa.h */
    FS_SERVER_CACHE_CACHESTATE_H,    /* fs/server/cache/cachestate.h */
    FS_SERVER_CACHE_CACHEMSG_H,    /* fs/server/cache/cachemsg.h */
    FS_SERVER_CACHE_CACHEMGR_H,    /* fs/server/cache/cachemgr.h */
    FS_SERVER_CACHE_CACHEWA_H,    /* fs/server/cache/cachewa.h */
    FS_SERVER_CACHE_CACHEDMRWA_H,    /* fs/server/cache/cachedmrwa.h */
    FS_SERVER_REPLICATION_RESYNCWORKAREAS_H,    /* fs/server/replication/resyncworkareas.h */
    FS_SERVER_REPLICATION_REPLCOMMON_H,    /* fs/server/replication/replcommon.h */
    FS_SERVER_REPLICATION_PRECOMMITWA_H,    /* fs/server/replication/precommitwa.h */
    FS_SERVER_REPLICATION_CONTAINERRESTOREWA_H,    /* fs/server/replication/containerrestorewa.h */
    FS_SERVER_REPLICATION_INODEITERATOR_H,    /* fs/server/replication/inodeiterator.h */
    FS_SERVER_REPLICATION_RESYNCPROC_H,    /* fs/server/replication/resyncproc.h */
    FS_SERVER_REPLICATION_REPLICATE_H,    /* fs/server/replication/replicate.h */
    FS_SERVER_REPLICATION_BECOMEMASTERWA_H,    /* fs/server/replication/becomemasterwa.h */
    FS_SERVER_REPLICATION_RPCBINDINGSCACHE_H,    /* fs/server/replication/rpcbindingscache.h */
    FS_SERVER_REPLICATION_VNBUCKET_H,    /* fs/server/replication/vnbucket.h */
    FS_SERVER_REPLICATION_BUCKETMGRINFO_H,    /* fs/server/replication/bucketmgrinfo.h */
    FS_SERVER_REPLICATION_ROLLBACKRESYNCCONTAINER_H,    /* fs/server/replication/rollbackresynccontainer.h */
    FS_SERVER_REPLICATION_REPLICAINFOWA_H,    /* fs/server/replication/replicainfowa.h */
    FS_SERVER_REPLICATION_VNSPACE_IMPL_H,    /* fs/server/replication/vnspace.impl.h */
    FS_SERVER_REPLICATION_FIRSTWRITEWA_H,    /* fs/server/replication/firstwritewa.h */
    FS_SERVER_REPLICATION_REPLICATIONWA_H,    /* fs/server/replication/replicationwa.h */
    FS_SERVER_REPLICATION_WAITLIST_H,    /* fs/server/replication/waitlist.h */
    FS_SERVER_REPLICATION_REPLCHAIN_H,    /* fs/server/replication/replchain.h */
    FS_SERVER_REPLICATION_VNSPACE_H,    /* fs/server/replication/vnspace.h */
    FS_SERVER_REPLICATION_RESYNCCONSTS_H,    /* fs/server/replication/resyncconsts.h */
    FS_SERVER_REPLICATION_WRITEBUCKETMGR_H,    /* fs/server/replication/writebucketmgr.h */
    FS_SERVER_REPLICATION_TXNBUCKETMGR_H,    /* fs/server/replication/txnbucketmgr.h */
    FS_SERVER_REPLICATION_INODEITERRANGEBUF_H,    /* fs/server/replication/inodeiterrangebuf.h */
    FS_SERVER_REPLICATION_INODERESYNCWALIST_H,    /* fs/server/replication/inoderesyncwalist.h */
    FS_SERVER_REPLICATION_VOLUMEMIRRORWA_H,    /* fs/server/replication/volumemirrorwa.h */
    FS_SERVER_REPLICATION_INODERESYNCSENDWALIST_H,    /* fs/server/replication/inoderesyncsendwalist.h */
    FS_SERVER_REPLICATION_CONTAINERREPLAYWA_H,    /* fs/server/replication/containerreplaywa.h */
    FS_SERVER_REPLICATION_INODERESYNCWA_H,    /* fs/server/replication/inoderesyncwa.h */
    FS_SERVER_REPLICATION_INODERESYNCSENDWA_H,    /* fs/server/replication/inoderesyncsendwa.h */
    FS_SERVER_REPLICATION_BUCKETMGR_H,    /* fs/server/replication/bucketmgr.h */
    FS_SERVER_REPLICATION_DUMPCMP_H,    /* fs/server/replication/dumpcmp.h */
    FS_SERVER_REPLICATION_REPLICATEOPS_H,    /* fs/server/replication/replicateops.h */
    FS_SERVER_REPLICATION_REPLICATIONMGR_H,    /* fs/server/replication/replicationmgr.h */
    FS_SERVER_REPLICATION_VOLUMEMIRROR_H,    /* fs/server/replication/volumemirror.h */
    FS_SERVER_REPLICATION_NODEFAILUREWA_H,    /* fs/server/replication/nodefailurewa.h */
    FS_SERVER_REPLICATION_CONTAINERRESYNCWA_H,    /* fs/server/replication/containerresyncwa.h */
    FS_SERVER_REPLICATION_REPLICAINFO_H,    /* fs/server/replication/replicainfo.h */
    FS_SERVER_REPLICATION_WRITEBUCKET_H,    /* fs/server/replication/writebucket.h */
    FS_SERVER_REPLICATION_REPLICATIONSERVER_H,    /* fs/server/replication/replicationserver.h */
    FS_SERVER_REPLICATION_RESYNCRECORDITERATORS_H,    /* fs/server/replication/resyncrecorditerators.h */
    FS_SERVER_REPLICATION_WRITEBUCKETMGRWA_H,    /* fs/server/replication/writebucketmgrwa.h */
    FS_SERVER_REPLICATION_TXNBUCKET_H,    /* fs/server/replication/txnbucket.h */
    FS_SERVER_REPLICATION_RESYNCHANDLES_H,    /* fs/server/replication/resynchandles.h */
    FS_SERVER_REPLICATION_DUMPFILE_H,    /* fs/server/replication/dumpfile.h */
    FS_SERVER_REPLICATION_TABLERESYNCBUF_H,    /* fs/server/replication/tableresyncbuf.h */
    FS_SERVER_REPLICATION_IDLERESYNCCHECKER_H,    /* fs/server/replication/idleresyncchecker.h */
    FS_SERVER_REPLICATION_VNHOLEWA_H,    /* fs/server/replication/vnholewa.h */
    FS_SERVER_TOOLS_MAPRSTAT_MAPRSTAT_C,    /* fs/server/tools/maprstat/maprstat.c */
    FS_SERVER_TOOLS_MAPRSTAT_CPUSTAT_C,    /* fs/server/tools/maprstat/cpustat.c */
    FS_SERVER_TOOLS_MAPRSTAT_MAPRSTAT_H,    /* fs/server/tools/maprstat/maprstat.h */
    FS_SERVER_TOOLS_MAPRSTAT_DISKSTAT_C,    /* fs/server/tools/maprstat/diskstat.c */
    FS_SERVER_CLEANER_DCLUSTER_H,    /* fs/server/cleaner/dcluster.h */
    FS_SERVER_CLEANER_BCLEANERWA_H,    /* fs/server/cleaner/bcleanerwa.h */
    FS_SERVER_CLEANER_IBIN_H,    /* fs/server/cleaner/ibin.h */
    FS_SERVER_CLEANER_ICLEANER_H,    /* fs/server/cleaner/icleaner.h */
    FS_SERVER_CLEANER_CLEANERWA_H,    /* fs/server/cleaner/cleanerwa.h */
    FS_SERVER_CLEANER_BCLEANER_H,    /* fs/server/cleaner/bcleaner.h */
    FS_SERVER_CLEANER_CLEANER_H,    /* fs/server/cleaner/cleaner.h */
    FS_SERVER_CLEANER_DCLEANER_H,    /* fs/server/cleaner/dcleaner.h */
    FS_SERVER_PCLDB_PCLDB_H,    /* fs/server/pcldb/pcldb.h */
    FS_SERVER_PCLDB_VOLCLIENT_H,    /* fs/server/pcldb/volclient.h */
    FS_SERVER_PCLDB_PCLDBWA_H,    /* fs/server/pcldb/pcldbwa.h */
    FS_SERVER_ORPHANAGE_ORPHANAGEWA_H,    /* fs/server/orphanage/orphanagewa.h */
    FS_SERVER_ORPHANAGE_ORPHANAGE_H,    /* fs/server/orphanage/orphanage.h */
    FS_SERVER_TRANS_TRANS_H,    /* fs/server/trans/trans.h */
    FS_SERVER_TRANS_BTREETRANS_H,    /* fs/server/trans/btreetrans.h */
    FS_SERVER_TRANS_MSTRANS_H,    /* fs/server/trans/mstrans.h */
    FS_SERVER_TRANS_TRANSWA_H,    /* fs/server/trans/transwa.h */
    FS_SERVER_IO_SPERROR_H,    /* fs/server/io/sperror.h */
    FS_SERVER_IO_IOMGR_H,    /* fs/server/io/iomgr.h */
    FS_SERVER_IO_LUN_H,    /* fs/server/io/lun.h */
    FS_SERVER_IO_SPCWA_H,    /* fs/server/io/spcwa.h */
    FS_SERVER_IO_IOCBWA_H,    /* fs/server/io/iocbwa.h */
    FS_SERVER_IO_SPSERVER_H,    /* fs/server/io/spserver.h */
    FS_SERVER_IO_BTREEBUF_H,    /* fs/server/io/btreebuf.h */
    FS_SERVER_IO_IODISPATCH_H,    /* fs/server/io/iodispatch.h */
    FS_SERVER_IO_SPIWA_H,    /* fs/server/io/spiwa.h */
    FS_SERVER_IO_CONFIGDG_H,    /* fs/server/io/configdg.h */
    FS_SERVER_IO_IOMSG_H,    /* fs/server/io/iomsg.h */
    FS_SERVER_IO_CONFIGSP_H,    /* fs/server/io/configsp.h */
    FS_SERVER_IO_IOLUN_H,    /* fs/server/io/iolun.h */
    FS_SERVER_IO_SP_H,    /* fs/server/io/sp.h */
    FS_SERVER_IO_CONFIG_H,    /* fs/server/io/config.h */
    FS_SERVER_MAPSERVER_SERVERINFO_H,    /* fs/server/mapserver/serverinfo.h */
    FS_SERVER_MAPSERVER_MSSPREFSWA_H,    /* fs/server/mapserver/mssprefswa.h */
    FS_SERVER_MAPSERVER_READAHEADBUF_H,    /* fs/server/mapserver/readaheadbuf.h */
    FS_SERVER_MAPSERVER_LOCKS_H,    /* fs/server/mapserver/locks.h */
    FS_SERVER_MAPSERVER_UTILWA_H,    /* fs/server/mapserver/utilwa.h */
    FS_SERVER_MAPSERVER_LOCKWA_H,    /* fs/server/mapserver/lockwa.h */
    FS_SERVER_MAPSERVER_VOLUMEWA_H,    /* fs/server/mapserver/volumewa.h */
    FS_SERVER_MAPSERVER_TRUNCOPSWA_H,    /* fs/server/mapserver/truncopswa.h */
    FS_SERVER_MAPSERVER_WRITE_WRITEFILEWA_H,    /* fs/server/mapserver/write/writefilewa.h */
    FS_SERVER_MAPSERVER_WRITE_CDMUTATOR_H,   /* fs/server/mapserver/write/cdmutator.h */
    FS_SERVER_MAPSERVER_WRITE_WRITECLUSTER_H,/* fs/server/mapserver/write/writecluster.h */
    FS_SERVER_MAPSERVER_WRITE_WPAGE_H,       /* fs/server/mapserver/write/wpage.h */
    FS_SERVER_MAPSERVER_REQUESTHANDLE_H,    /* fs/server/mapserver/requesthandle.h */
    FS_SERVER_MAPSERVER_READAHEADMGR_H,    /* fs/server/mapserver/readaheadmgr.h */
    FS_SERVER_MAPSERVER_KVSTORE_H,    /* fs/server/mapserver/kvstore.h */
    FS_SERVER_MAPSERVER_DEFERWA_H,    /* fs/server/mapserver/deferwa.h */
    FS_SERVER_MAPSERVER_READFILELETWA_H,    /* fs/server/mapserver/readfileletwa.h */
    FS_SERVER_MAPSERVER_FILEPREFETCHWA_H,    /* fs/server/mapserver/fileprefetchwa.h */
    FS_SERVER_MAPSERVER_COMMITWA_H,    /* fs/server/mapserver/commitwa.h */
    FS_SERVER_MAPSERVER_FILESERVER_H,    /* fs/server/mapserver/fileserver.h */
    FS_SERVER_MAPSERVER_PERMISSIONS_H,    /* fs/server/mapserver/permissions.h */
    FS_SERVER_MAPSERVER_COPYFIDSWA_H,    /* fs/server/mapserver/copyfidswa.h */
    FS_SERVER_MAPSERVER_CTABLE_H,    /* fs/server/mapserver/ctable.h */
    FS_SERVER_MAPSERVER_CIDCACHE_H,    /* fs/server/mapserver/cidcache.h */
    FS_SERVER_MAPSERVER_REMOTEFS_H,    /* fs/server/mapserver/remotefs.h */
    FS_SERVER_MAPSERVER_ALLOCATEFIDWA_H,    /* fs/server/mapserver/allocatefidwa.h */
    FS_SERVER_MAPSERVER_SERVERCOMMAND_H,    /* fs/server/mapserver/servercommand.h */
    FS_SERVER_MAPSERVER_DIRHASHENT_H,    /* fs/server/mapserver/dirhashent.h */
    FS_SERVER_MAPSERVER_WRITEFILELETWA_H,    /* fs/server/mapserver/writefileletwa.h */
    FS_SERVER_MAPSERVER_VALIDATERPC_H,    /* fs/server/mapserver/validaterpc.h */
    FS_SERVER_MAPSERVER_SERVERCOMMANDWA_H,    /* fs/server/mapserver/servercommandwa.h */
    FS_SERVER_MAPSERVER_CLUSTERDECOMPRESS_H,    /* fs/server/mapserver/clusterdecompress.h */
    FS_SERVER_MAPSERVER_GETFIDMAPWA_H,    /* fs/server/mapserver/getfidmapwa.h */
    FS_SERVER_MAPSERVER_DEFERTREEWA_H,    /* fs/server/mapserver/defertreewa.h */
    FS_SERVER_MAPSERVER_GETWRITEDATA_H,    /* fs/server/mapserver/getwritedata.h */
    FS_SERVER_MAPSERVER_GETFILELETSZWA_H,    /* fs/server/mapserver/getfileletszwa.h */
    FS_SERVER_MAPSERVER_PURGEFIDMAPWA_H,    /* fs/server/mapserver/purgefidmapwa.h */
    FS_SERVER_MAPSERVER_KVSTOREWA_H,    /* fs/server/mapserver/kvstorewa.h */
    FS_SERVER_MAPSERVER_CREATEWA_H,    /* fs/server/mapserver/createwa.h */
    FS_SERVER_MAPSERVER_SHARDWA_H,    /* fs/server/mapserver/shardwa.h */
    FS_SERVER_MAPSERVER_DIROPSWA_H,    /* fs/server/mapserver/diropswa.h */
    FS_SERVER_MAPSERVER_REMOTEFSWA_H,    /* fs/server/mapserver/remotefswa.h */
    FS_SERVER_MAPSERVER_MAPSERVER_H,    /* fs/server/mapserver/mapserver.h */
    FS_SERVER_MAPSERVER_CIDCACHEWA_H,    /* fs/server/mapserver/cidcachewa.h */
    FS_SERVER_MAPSERVER_CLUSTERDECOMPRESSWA_H,    /* fs/server/mapserver/clusterdecompresswa.h */
    FS_SERVER_MAPSERVER_READDIRBUF_H,    /* fs/server/mapserver/readdirbuf.h */
    FS_SERVER_MAPSERVER_TRUNCOPS_H,    /* fs/server/mapserver/truncops.h */
    FS_SERVER_MAPSERVER_FILESERVERWA_H,    /* fs/server/mapserver/fileserverwa.h */
    FS_SERVER_MAPSERVER_READAHEADWA_H,    /* fs/server/mapserver/readaheadwa.h */
    FS_SERVER_MAPSERVER_SHARD_H,    /* fs/server/mapserver/shard.h */
    FS_SERVER_MAPSERVER_SETFILELETSZWA_H,    /* fs/server/mapserver/setfileletszwa.h */
    FS_SERVER_LOG_PLI_H,    /* fs/server/log/pli.h */
    FS_SERVER_LOG_RECOVERY_H,    /* fs/server/log/recovery.h */
    FS_SERVER_LOG_RECORDS_H,    /* fs/server/log/records.h */
    FS_SERVER_LOG_TXN_H,    /* fs/server/log/txn.h */
    FS_SERVER_LOG_PAGE_H,    /* fs/server/log/page.h */
    FS_SERVER_LOG_LOG_H,    /* fs/server/log/log.h */
    FS_SERVER_LOG_LOGWA_H,    /* fs/server/log/logwa.h */
    FS_SERVER_LOG_CRC32_H,    /* fs/server/log/crc32.h */
    FS_NFSD_NFS_H,    /* fs/nfsd/nfs.h */
    FS_NFSD_REQUESTHANDLE_H,    /* fs/nfsd/requesthandle.h */
    FS_NFSD_LOG_H,    /* fs/nfsd/log.h */
    FS_NFSD_UTILS_H,    /* fs/nfsd/utils.h */
    FS_NFSD_NFS_XDR_C,    /* fs/nfsd/nfs_xdr.c */
    FS_NFSD_NFSCOMMON_H,    /* fs/nfsd/nfscommon.h */
    FS_NFSD_NFSSERVER_H,    /* fs/nfsd/nfsserver.h */
    FS_NFSD_MOUNT_H,    /* fs/nfsd/mount.h */
    FS_NFSD_MOUNT_XDR_C,    /* fs/nfsd/mount_xdr.c */
    FS_NFSD_CONFIG_H,    /* fs/nfsd/config.h */
    FS_SERVER_DB_BLOCKREADER_CC,  /* fs/server/db/blockreader.cc */
    FS_SERVER_DB_BUCKETFLUSH_CC,  /* fs/server/db/bucketflush.cc */
    FS_SERVER_DB_BUCKETROWFETCHER_CC,  /* fs/server/db/bucketrowfetcher.cc */
    FS_SERVER_DB_BUCKETSCANNER_CC,  /* fs/server/db/bucketscanner.cc */
    FS_SERVER_DB_CIDMAP_CC,  /* fs/server/db/cidmap.cc */
    FS_SERVER_DB_CIDMAPCACHE_CC,  /* fs/server/db/cidmapcache.cc */
    FS_SERVER_DB_PERMISSIONS_ACE_EVALUATOR_CC, /* fs/server/db/permissions/ace_evaluator.cc */
    FS_SERVER_DB_PERMISSIONS_COL_SET_CC, /* fs/server/db/permissions/col_set.cc */
    FS_SERVER_DB_PERMISSIONS_ROLE_MEMBERSHIP_CC, /* fs/server/db/permissions/role_membership.cc */
    FS_SERVER_DB_PERMISSIONS_ROLERESOLVER_CC, /* fs/server/db/permissions/roleresolver.cc */
    FS_SERVER_DB_DBSERVER_CC,  /* fs/server/db/dbserver.cc */
    FS_SERVER_DB_LKMGR_CC,  /* fs/server/db/lkmgr.cc */
    FS_SERVER_DB_LOCALREQ_CC, /* fs/server/db/localreq.cc */
    FS_SERVER_DB_REMOTEDELS_CC, /* fs/server/db/remotedels.cc */
    FS_SERVER_DB_LOGREADER_CC,  /* fs/server/db/logreader.cc */
    FS_SERVER_DB_LOGWRITER_CC,  /* fs/server/db/logwriter.cc */
    FS_SERVER_DB_MEMINDEX_CC,  /* fs/server/db/memindex.cc */
    FS_SERVER_DB_MEMINDEXSCANNER_CC,  /* fs/server/db/memindexscanner.cc */
    FS_SERVER_DB_MERGESCANNER_CC,  /* fs/server/db/mergescanner.cc */
    FS_SERVER_DB_MERGEONLYSCANNER_CC,  /* fs/server/db/mergeonlyscanner.cc */
    FS_SERVER_DB_MFSOPS_CC,  /* fs/server/db/mfsops.cc */
    FS_SERVER_DB_MFSREAD_CC,  /* fs/server/db/mfsread.cc */
    FS_SERVER_DB_MFSWRITE_CC,  /* fs/server/db/mfswrite.cc */
    FS_SERVER_DB_MFSUPCALLS_CC,  /* fs/server/db/mfsupcalls.cc */
    FS_SERVER_DB_PARTITION_CC,  /* fs/server/db/partition.cc */
    FS_SERVER_DB_PARTITIONMAP_CC,  /* fs/server/db/partitionmap.cc */
    FS_SERVER_DB_SEGMENT_CC,  /* fs/server/db/segment.cc */
    FS_SERVER_DB_SEGMENTSCANNER_CC,  /* fs/server/db/segmentscanner.cc */
    FS_SERVER_DB_SPILL_CC,  /* fs/server/db/spill.cc */
    FS_SERVER_DB_SPILLSCANNER_CC,  /* fs/server/db/spillscanner.cc */
    FS_SERVER_DB_SORTEDBUCKETSCANNER_CC,  /* fs/server/db/sortedbucketscanner.cc */
    FS_SERVER_DB_MFSSPILLWRITER_CC,  /* fs/server/db/mfsspillwriter.cc */
    FS_SERVER_DB_SPILLWRITER_CC,  /* fs/server/db/spillwriter.cc */
    FS_SERVER_DB_TRANSFORM_ROW_CC,  /* fs/server/db/transformrow.cc */
    FS_SERVER_DB_TABLE_CC,  /* fs/server/db/table.cc */
    FS_SERVER_DB_TABLET_CC,  /* fs/server/db/tablet.cc */
    FS_SERVER_DB_TABLETBUCKET_CC,  /* fs/server/db/tabletbucket.cc */
    FS_SERVER_DB_TABLETMERGE_CC,  /* fs/server/db/tabletmerge.cc */
    FS_SERVER_DB_TABLETMERGESRC_CC,  /* fs/server/db/tabletmergesrc.cc */
    FS_SERVER_DB_TABLETOPS_CC,  /* fs/server/db/tabletops.cc */
    FS_SERVER_DB_TABLETSPLIT_CC,  /* fs/server/db/tabletsplit.cc */
    FS_SERVER_DB_TABLETSCANNER_CC,  /* fs/server/db/tabletscanner.cc */
    FS_SERVER_DB_TABLESCHEMACACHE_CC, /* fs/server/db/tableschemacache.cc */
    FS_SERVER_DB_VALUECACHE_CC, /* fs/server/db/valuecache.cc */
    FS_SERVER_DB_IMPORTSEGMENT_CC,  /* fs/server/db/importsegment.cc */
    FS_SERVER_DB_IMPORTBUCKET_CC,  /* fs/server/db/importbucket.cc */
    FS_SERVER_DB_READ_SEGMENTGET_CC,  /* fs/server/db/read/segmentget.cc */
    FS_SERVER_DB_READ_SPILLGET_CC,  /* fs/server/db/read/spillget.cc */
    FS_SERVER_DB_READ_SORTEDBUCKETREADER_CC,  /* fs/server/db/sortedbucketreader.cc */
    FS_SERVER_DB_RPC_APPEND_CC,  /* fs/server/db/rpc/append.cc */
    FS_SERVER_DB_RPC_ATTR_CC,  /* fs/server/db/rpc/attr.cc */
    FS_SERVER_DB_RPC_CFCREATE_CC, /* fs/server/db/rpc/cfcreate.cc */
    FS_SERVER_DB_RPC_CFDELETE_CC, /* fs/server/db/rpc/cfdelete.cc */
    FS_SERVER_DB_RPC_CFMODIFY_CC, /* fs/server/db/rpc/cfmodify.cc */
    FS_SERVER_DB_RPC_CFSCAN_CC,   /* fs/server/db/rpc/cfscan.cc */
    FS_SERVER_DB_RPC_CFUTIL_CC,   /* fs/server/db/rpc/cfutil.cc */
    FS_SERVER_DB_RPC_CHECKANDPUT_CC,  /* fs/server/db/rpc/checkandput.cc */
    FS_SERVER_DB_RPC_COMPACT_CC,  /* fs/server/db/rpc/compact.cc */
    FS_SERVER_DB_RPC_CRAFT_CC,  /* fs/server/db/rpc/craft.cc */
    FS_SERVER_DB_RPC_GET_CC,  /* fs/server/db/rpc/get.cc */
    FS_SERVER_DB_RPC_INCREMENT_CC,  /* fs/server/db/rpc/increment.cc */
    FS_SERVER_DB_RPC_INFO_CC, /* fs/server/db/rpc/info.cc */
    FS_SERVER_DB_RPC_PUT_CC,  /* fs/server/db/rpc/put.cc */
    FS_SERVER_DB_RPC_REQUTIL_CC,  /* fs/server/db/rpc/requtil.cc */
    FS_SERVER_DB_RPC_SCAN_CC,  /* fs/server/db/rpc/scan.cc */
    FS_SERVER_DB_RPC_SCHEMAREFRESH_CC, /* fs/server/db/rpc/schemarefresh.cc */
    FS_SERVER_DB_RPC_STAT_CC, /* fs/server/db/rpc/stat.cc */
    FS_SERVER_DB_RPC_TABLETLOOKUP_CC, /* fs/server/db/rpc/tabletlookup.cc */
    FS_SERVER_DB_RPC_TESTSCAN_CC, /* fs/server/db/rpc/testscan.cc */
    FS_SERVER_DB_RPC_RAWSPILLSCAN_CC, /* fs/server/db/rpc/rawspillscan.cc */
    FS_SERVER_DB_RPC_ROLESCACHE_CC, /* fs/server/db/rpc/rolescache.cc */
    FS_SERVER_DB_RPC_IMPORTSEGMENTRPC_CC,  /* fs/server/db/rpc/importsegmentrpc.cc */
    FS_SERVER_DB_RPC_GETPARTITONSPLITS_CC,  /* fs/server/db/rpc/getpartitionsplits.cc */
    FS_SERVER_DB_RPC_IMPORTBUCKETRPC_CC,  /* fs/server/db/rpc/importbucketrpc.cc */
    FS_SERVER_DB_LDB_BLOCK_CC, /* fs/server/db/ldb/block.cc */
    FS_SERVER_DB_LDB_BLOCKBUILDER_CC, /* fs/server/db/ldb/block_builder.cc */
    FS_SERVER_DB_LDB_TABLE_CC, /* fs/server/db/ldb/table.cc */
    FS_SERVER_DB_LDB_TABLEBUILDER_CC, /* fs/server/db/ldb/table_builder.cc */
    FS_SERVER_DB_LDB_TABLEWRITER_CC, /* fs/server/db/ldb/tablewriter.cc */
    FS_SERVER_DB_FILTERS_APPLYFILTER_CC, /* fs/server/db/filters/applyfilter.cc */
    FS_SERVER_DB_FILTERS_SCANNERWITHFILTER_CC, /* fs/server/db/filters/scannerwithfilter.cc */
    FS_SERVER_DB_FILTERS_FILTERMANAGER_TEST_CC, /* fs/server/db/filters/filtermanager_test.cc */
    FS_SERVER_DB_TEST_TEDSERVER_CC, /*fs/server/db/test/tedserver.cc*/
    FS_SERVER_DB_TEST_TED_CC,    /* fs/server/db/test/ted.cc */
    FS_SERVER_CLDB_JNI_CC,
    FS_CLIENT_FILECLIENT_CC_JNI_KVSTORECLIENT_CC, /* fs/client/fileclient/cc/jni_KvStoreClient.cc */
    FS_CLIENT_FILECLIENT_CC_JNI_MAPRTABLETOOLS_CC,    /* fs/client/fileclient/cc/jni_MapRTableTools.cc */
    FS_CLIENT_FILECLIENT_CC_JNI_MAPRCLIENT_CC, /* fs/client/fileclient/cc/jni_MapRClient.cc */
    FS_CLIENT_FILECLIENT_CC_MAPR_JNI_INC_H, /* fs/client/fileclient/cc/mapr_jni_inc.h */
    FS_CLIENT_FILECLIENT_CC_MAPR_JNI_KV_H, /* fs/client/fileclient/cc/mapr_jni_kv.h */
    FS_CLIENT_FILECLIENT_CC_MAPR_JNI_SCAN_H, /* fs/client/fileclient/cc/mapr_jni_scan.h */
    FS_CLIENT_FILECLIENT_CC_MAPR_JNI_COMMON_H, /* fs/client/fileclient/cc/mapr_jni_common.h */
    FS_CLIENT_FILECLIENT_CC_MAPR_JNI_PUT_H, /* fs/client/fileclient/cc/mapr_jni_put.h */
    FS_CLIENT_FILECLIENT_CC_MAPR_JNI_RESULT_H, /* fs/client/fileclient/cc/mapr_jni_result.h */
    FS_CLIENT_FILECLIENT_CC_API_COMMON_CC, /*fs/client/fileclient/cc/api_common.cc */
    Total
  }; //enum
} //FileId

extern const char *FileIdInfo[FileId::Total + 1];
#define GetFileIdStr(m) FileIdInfo[(m)]
} // fs
} // mapr
#endif //FILEIDS_H__
